'use strict';
const $=s=>document.querySelector(s);
const art={rooms:'assets/rooms.png',dolls:'assets/dolls-wavy.png',accessories:'assets/accessories.png',quilt:'assets/quilt.png',bathroom:'assets/bathroom.png',bathItems:'assets/bath-items.png',wetDolls:'assets/wet-dolls.png',ponytailDolls:'assets/ponytail-dolls.png',playKitty:'assets/play-strawberry-chibs.png',pinkHello:'audio/lily-girly.wav',cherryHello:'audio/cherry-invite.wav',kittyMeow:'audio/kitty-meow.wav',lilyPlay:'audio/lily-seek.wav',cherryPlay:'audio/cherry-found.wav',lilyDress:'audio/lily-dress.wav',cherryDress:'audio/cherry-dress.wav',lilyEat:'audio/lily-pancakes.wav',cherryEat:'audio/cherry-pancakes.wav'};
const names=['Bedroom','Closet','Bathroom','Makeup'];
const captions=['A little place to dream','Something strawberry to wear','A little splash of strawberry','A little getting-ready time'];
const crops={girl:[70,0,535,738],friend:[670,0,535,738],cat:[65,744,540,510],blanket:[657,742,575,512]};
const definitions=[
 {id:'girl',name:'Lily',sheet:'dolls',crop:'girl',page:0,x:37,y:55,w:34,kind:'doll'},
 {id:'friend',name:'Cherry',sheet:'dolls',crop:'friend',page:3,x:51,y:76,w:34,kind:'doll'},
 {id:'cat',name:'Chibs',sheet:'dolls',crop:'cat',page:0,x:83,y:77,w:21,kind:'cat'},
 {id:'pinafore',name:'Strawberry pinafore',tile:0,page:1,x:22,y:28,w:24,slot:'outfit'},
 {id:'dress',name:'Red bow dress',tile:1,page:1,x:22,y:44,w:25,slot:'outfit'},
 {id:'smile-shoes',name:'Smiley strawberry shoes',tile:2,page:1,x:42,y:49,w:17,slot:'shoes'},
 {id:'bow-shoes',name:'Strawberry bow shoes',tile:3,page:1,x:42,y:58,w:17,slot:'shoes'},
 {id:'bonnet',name:'Strawberry headband',tile:4,page:1,x:42,y:23,w:19,slot:'hat'},
 {id:'bag',name:'Strawberry bag',tile:5,page:3,x:14,y:45,w:18,slot:'bag'},
 {id:'bow',name:'Strawberry hair bow',tile:6,page:3,x:82,y:17,w:15,slot:'bow'},
 {id:'glasses',name:'Pink glasses',tile:7,page:3,x:19,y:18,w:17,slot:'glasses'},
 {id:'brush',name:'Big makeup brush',tile:8,page:3,x:16,y:56,w:16,kind:'makeup'},
 {id:'small-brush',name:'Little makeup brush',tile:9,page:3,x:85,y:57,w:13,kind:'makeup'},
 {id:'lipstick',name:'Strawberry lipstick',tile:10,page:3,x:85,y:42,w:13,kind:'makeup'},
 {id:'foundation',name:'Peach compact',tile:12,page:3,x:48,y:47,w:19,fixed:true},
 {id:'cream',name:'Strawberry cream',tile:13,page:3,x:65,y:47,w:16,fixed:true},
 {id:'palette',name:'Three-color palette',tile:14,page:3,x:31,y:47,w:17,fixed:true},
 {id:'foundation-lid',name:'Peach compact lid',tile:11,page:3,x:48,y:47,w:19,lidFor:'foundation',closed:true},
 {id:'cream-lid',name:'Cream lid',tile:11,page:3,x:65,y:43,w:14,lidFor:'cream',closed:true},
 {id:'palette-lid',name:'Palette lid',tile:11,page:3,x:31,y:47,w:17,lidFor:'palette',closed:true},
 {id:'toothbrush',name:'Strawberry toothbrush',sheet:'bathItems',tile:0,page:2,x:80,y:39,w:13,kind:'toothbrush'},
 {id:'robe',name:'Pink bathrobe',sheet:'bathItems',tile:1,page:2,x:44,y:39,w:23,slot:'outfit'},
 {id:'soap',name:'Strawberry soap',sheet:'bathItems',tile:2,page:2,x:89,y:59,w:13,kind:'soap'},
 {id:'towel',name:'Pink towel',sheet:'bathItems',tile:3,page:2,x:89,y:48,w:17,kind:'towel'},
 {id:'clip-left',name:'Left strawberry hair clip',tile:15,page:0,x:27,y:40,w:7,slot:'clipLeft',attached:'girl'},
 {id:'clip-right',name:'Right strawberry hair clip',tile:15,page:0,x:47,y:40,w:7,slot:'clipRight',attached:'girl'}
].map(d=>({sheet:'accessories',...d}));
let state={residencyVersion:4,page:0,opened:false,coverSide:'front',blanketOpen:false,catFed:false,pieces:definitions.map(d=>({...d})),makeup:{}};
let selected=null,drag=null,z=30,toastTimer,heldClothing=null;
const slotLayout={outfit:[.5,.65,.66],shoes:[.5,.94,.31],hat:[.5,.11,.85],bag:[.48,.70,.45],bow:[.77,.15,.30],glasses:[.5,.34,.60],clipLeft:[.20,.16,.23],clipRight:[.80,.16,.23]};
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
function cropFor(p){if(p.id==='cat'&&state.catPlaying&&state.page===1)return[640,35,575,655];if(p.sheet==='bathItems')return[(p.tile%2)*627,Math.floor(p.tile/2)*627,627,627];if(p.sheet==='dolls')return crops[p.crop];if(p.tile===0)return[35,55,280,270];if(p.tile===1)return[332,55,294,270];if(p.tile===2)return[638,94,292,224];if(p.tile===3)return[954,94,284,224];if(p.tile===5)return[332,370,295,242];const rows=[0,325,635,930,1254];let row=Math.floor(p.tile/4);return[(p.tile%4)*313.5,rows[row],313.5,rows[row+1]-rows[row]];}
function spriteStyle(el,p){const [x,y,w,h]=cropFor(p),size=1254;el.style.backgroundImage=`url("${art[p.id==='cat'&&state.catPlaying&&state.page===1?'playKitty':p.sheet==='dolls'&&p.id==='girl'?(state.wetHair?'wetDolls':'dolls'):p.sheet]}")`;el.style.backgroundSize=`${size/w*100}% ${size/h*100}%`;el.style.backgroundPosition=`${x/(size-w)*100}% ${y/(size-h)*100}%`;}
function dims(p){const c=cropFor(p);return {w:p.w,h:p.w*c[3]/c[2]/1.5};}
function visual(p){if(!p.attached)return{...p,...dims(p)};const parent=state.pieces.find(q=>q.id===p.attached);if(!parent)return{...p,...dims(p)};const l=slotLayout[p.slot],pd=dims(parent),w=parent.w*l[2];const h=w*cropFor(p)[3]/cropFor(p)[2]/1.5;return{...p,page:parent.page,x:parent.x+parent.w*(l[0]-.5),y:parent.y+pd.h*(l[1]-.5),w,h};}
function restore(raw){if(!raw||typeof raw!=='object'||!Array.isArray(raw.pieces))return false;if((raw.residencyVersion||0)<4){raw={...raw,page:raw.page===2?3:raw.page,pieces:raw.pieces.map(p=>({...p,page:p.page===2?3:p.page}))};}state.page=Number.isInteger(raw.page)?clamp(raw.page,0,3):0;state.opened=Boolean(raw.opened);state.coverSide=raw.coverSide==='back'?'back':'front';state.bathing=raw.bathing===true;state.wetHair=raw.wetHair===true;state.highPonytail=raw.highPonytail===true;state.soundMuted=raw.soundMuted===true;state.brushed=['girl','friend'].includes(raw.brushed)?raw.brushed:null;state.blanketOpen=raw.blanketOpen===true;state.catFed=raw.catFed===true;state.catPlaying=raw.catPlaying===true;state.snacking=['girl','friend'].includes(raw.snacking)?raw.snacking:null;for(const p of state.pieces){const r=raw.pieces.find(q=>q&&q.id===p.id);if(!r)continue;if(!p.fixed){if(Number.isFinite(r.x))p.x=clamp(r.x,2,98);if(Number.isFinite(r.y))p.y=clamp(r.y,2,98);if(Number.isInteger(r.page))p.page=clamp(r.page,0,3);if(typeof r.attached==='string'&&p.slot&&['girl','friend'].includes(r.attached))p.attached=r.attached;else delete p.attached;if(p.lidFor)p.closed=r.closed===true;} }if(raw.makeup&&typeof raw.makeup==='object')for(const id of ['girl','friend'])state.makeup[id]={blush:raw.makeup[id]===true||raw.makeup[id]?.blush===true,lipstick:raw.makeup[id]?.lipstick===true};if((raw.residencyVersion||0)<3){const kitty=state.pieces.find(p=>p.id==='cat');kitty.page=0;kitty.x=83;kitty.y=77;}return true;}
try{const initial=JSON.parse($('#initial-state').textContent);if(initial)restore(initial);else restore(JSON.parse(localStorage.getItem('strawberry-butter-v2')));}catch{}
function save(){try{localStorage.setItem('strawberry-butter-v2',JSON.stringify(state));}catch{}}
const activeClips=new Set();let greetingVersion=0,kittyTimer=null,chatTimer=null,chatRound=0;
function playClip(key,done=()=>{}){if(state.soundMuted){done();return;}const clip=new Audio(art[key]);clip.volume=.65;activeClips.add(clip);const finish=()=>{activeClips.delete(clip);done();};clip.onended=finish;clip.onerror=finish;clip.play().catch(finish);}
function stopDialogue(){greetingVersion++;clearTimeout(chatTimer);chatTimer=null;for(const clip of activeClips){clip.onended=null;clip.pause();}activeClips.clear();$('#dialogue').hidden=true;}
function greetGirls(){if(state.page!==1||!state.opened||state.soundMuted||document.hidden)return;stopDialogue();const version=greetingVersion;const rounds=[['pinkHello','cherryHello'],['lilyPlay','cherryPlay'],['lilyDress','cherryDress']],pair=state.closetActivity==='eating'?['lilyEat','cherryEat']:rounds[chatRound++%rounds.length];playClip(pair[0],()=>{if(version!==greetingVersion||state.page!==1||!state.opened)return;playClip(pair[1],()=>{if(version===greetingVersion)chatTimer=setTimeout(greetGirls,1800);});});}
let playTimer=null,hideStep=0;
function stopClosetPlay(){clearTimeout(playTimer);playTimer=null;state.hidingGirl=null;}
function closetTurn(){if(state.page!==1||!state.opened||document.hidden||state.closetActivity!=='hide-seek')return;const lily=state.pieces.find(p=>p.id==='girl'),cherry=state.pieces.find(p=>p.id==='friend');lily.x=32;lily.y=78;cherry.x=65;cherry.y=78;state.hidingGirl=null;if(hideStep%4===0){state.hidingGirl='friend';cherry.x=70;cherry.y=66;}if(hideStep%4===2){state.hidingGirl='girl';lily.x=70;lily.y=66;cherry.x=30;}hideStep++;save();render();playTimer=setTimeout(closetTurn,4200);}
function startClosetPlay(){stopClosetPlay();state.closetActivity='hide-seek';state.snacking=null;hideStep=0;chatRound=0;const cat=state.pieces.find(p=>p.id==='cat');cat.page=1;cat.x=84;cat.y=84;state.catPlaying=true;state.catFed=false;save();render();greetGirls();playTimer=setTimeout(closetTurn,6000);}
function eatTogether(){stopClosetPlay();state.closetActivity='eating';for(const p of state.pieces.filter(p=>p.kind==='doll')){p.page=1;p.x=p.id==='girl'?15:39;p.y=74;}save();render();greetGirls();say('Lily and Cherry are eating pancakes');}
function syncKittyPlay(){const active=!!(state.opened&&state.page===1&&state.catPlaying&&state.pieces.find(p=>p.id==='cat').page===1);$('#sponge-toy').hidden=state.page!==1;$('#sponge-toy').classList.toggle('pulling',active);$('#sponge-toy').setAttribute('aria-label',active?'Stop Chibs pulling the sponge':'Play with the hanging sponge');$('#sponge-drawing').style.backgroundImage=`url("${art.playKitty}")`;if(kittyTimer){clearInterval(kittyTimer);kittyTimer=null;}if(active&&!state.soundMuted&&!document.hidden)kittyTimer=setInterval(()=>playClip('kittyMeow'),6500);}
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopDialogue();stopClosetPlay();}else if(state.page===1){greetGirls();if(state.closetActivity==='hide-seek')playTimer=setTimeout(closetTurn,4200);}syncKittyPlay();});
let audioContext;
function playSound(kind){if(state.soundMuted)return;if(kind==='kitty'){playClip('kittyMeow');return;}try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;audioContext ||= new Audio();if(audioContext.state==='suspended')audioContext.resume().catch(()=>{});const t=audioContext.currentTime;
 const tone=(hz,to,duration,delay=0)=>{const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.setValueAtTime(hz,t+delay);osc.frequency.exponentialRampToValueAtTime(to,t+delay+duration);gain.gain.setValueAtTime(.0001,t+delay);gain.gain.exponentialRampToValueAtTime(.055,t+delay+.015);gain.gain.exponentialRampToValueAtTime(.0001,t+delay+duration);osc.connect(gain).connect(audioContext.destination);osc.start(t+delay);osc.stop(t+delay+duration+.02);};
 const rustle=(duration,cutoff)=>{const buffer=audioContext.createBuffer(1,Math.ceil(audioContext.sampleRate*duration),audioContext.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.sin(Math.PI*i/data.length);const source=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter(),gain=audioContext.createGain();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=cutoff;gain.gain.value=.10;source.connect(filter).connect(gain).connect(audioContext.destination);source.start(t);};
 if(kind==='splash'){rustle(.45,2200);tone(570,220,.12,.08);tone(750,320,.15,.24);}else if(kind==='page'||kind==='cloth'){rustle(kind==='page'?.20:.13,kind==='page'?1800:900);}else if(kind==='kitty'){tone(620,410,.16);tone(470,330,.12,.16);}else{tone(700,950,.09);tone(950,1150,.10,.08);}
 }catch{/* Audio is optional; play stays available when unsupported. */}}
function say(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2400);}
function render(){$('#sound-toggle').textContent=state.soundMuted?'Sound off':'Sound on';$('#sound-toggle').setAttribute('aria-pressed',String(!state.soundMuted));for(const p of state.pieces.filter(p=>p.kind==='doll'))p.page=state.page===1?1:p.id==='girl'?(state.page===2?2:0):3;
 $('#cover-view').hidden=state.opened||state.coverSide==='back';$('#back-cover-view').hidden=state.opened||state.coverSide!=='back';$('#close-book').hidden=!state.opened;$('#play-view').hidden=!state.opened;
 $('#room').dataset.page=state.page;$('#room').setAttribute('aria-label',`${names[state.page]}. Move pieces with a pointer or arrow keys.`);
 const roomRects=[[0,0,566,887],[568,0,639,887],[1209,0,565,887]],r=roomRects[state.page===3?2:state.page];if(state.page===2){$('.room-art').style.backgroundImage=`url("${art.bathroom}")`;$('.room-art').style.backgroundSize='100% 100%';$('.room-art').style.backgroundPosition='center';}else{$('.room-art').style.backgroundImage=`url("${art.rooms}")`;$('.room-art').style.backgroundSize=`${1774/r[2]*100}% 100%`;$('.room-art').style.backgroundPosition=`${r[0]/(1774-r[2])*100}% 0`;}$('#bath-hit').hidden=state.page!==2;$('#bath-front').hidden=state.page!==2||!state.bathing;$('#bath-front').style.backgroundImage=`url("${art.bathroom}")`;$('#bath-bubbles').hidden=state.page!==2||!state.bathing;
 document.querySelectorAll('[data-page]').forEach(b=>{if(b.tagName==='BUTTON'){b.classList.toggle('active',+b.dataset.page===state.page);b.setAttribute('aria-current',+b.dataset.page===state.page?'page':'false');}});
 $('#page-caption').textContent=captions[state.page];$('#previous').disabled=state.page===0;$('#next').disabled=false;$('#next').setAttribute('aria-label',state.page===3?'Back cover':'Next page');
 $('#blanket').hidden=state.page!==0;$('#bed-toggle').hidden=state.page!==0;$('#feed-girl').hidden=state.page!==1;$('#play-kitty').hidden=state.page!==1;$('#feed-kitty').hidden=state.page!==0||!state.blanketOpen;$('#bed-toggle').textContent=state.blanketOpen?'Blanket is open':'Lift blanket';$('#bed-toggle').disabled=state.blanketOpen;$('#tuck-girl').hidden=state.page!==0;$('#blanket').classList.toggle('open',state.blanketOpen);$('#blanket').setAttribute('aria-expanded',String(state.blanketOpen));$('#blanket').style.backgroundImage=`url("${art.quilt}")`;$('#blanket').style.backgroundSize=`${1774/435*100}% ${887/211*100}%`;$('#blanket').style.backgroundPosition=`${31/(1774-435)*100}% ${474/(887-211)*100}%`;
 const pieces=$('#pieces');pieces.replaceChildren();
 for(const p of state.pieces){const v=visual(p);if(v.page!==state.page)continue;const el=document.createElement('button');el.className='piece'+(selected===p.id?' selected':'')+(p.id==='cat'&&state.catFed?' eating':'')+(p.id==='cat'&&state.page===1&&state.catPlaying?' playing':'')+(p.kind==='doll'&&state.page===1&&(state.snacking===p.id||state.closetActivity==='eating')?' snacking':'');el.dataset.id=p.id;el.dataset.character=p.attached||(p.kind==='doll'?p.id:'');el.dataset.worn=p.attached?'true':'false';el.setAttribute('aria-label',p.name+(p.fixed?', attached to the desk':p.attached?', worn by '+state.pieces.find(q=>q.id===p.attached).name:', movable'));el.title=p.name;position(el,v);const inBed=q=>q&&q.page===0&&q.x>15&&q.x<70&&q.y>35&&q.y<69;el.style.zIndex=p.fixed?5:p.attached?((inBed(state.pieces.find(q=>q.id===p.attached))||(state.page===2&&state.bathing&&p.attached==='girl'))?50:80):p.kind==='cat'?70:p.kind==='doll'&&state.page===0&&!inBed(p)?70:p.lidFor&&p.closed?25:20;if(state.page===1&&state.hidingGirl&&(p.id===state.hidingGirl||p.attached===state.hidingGirl))el.style.zIndex=p.attached?11:10;const sp=document.createElement('span');sp.className='sprite';spriteStyle(sp,p);el.append(sp);
 if(p.kind==='doll'&&state.brushed===p.id){const sparkle=document.createElement('span');sparkle.className='tooth-sparkle';sparkle.textContent='✧';el.append(sparkle);}if(p.kind==='doll'&&state.makeup[p.id]){if(state.makeup[p.id].blush){const blush=document.createElement('span');blush.className='blush';el.append(blush);}if(state.makeup[p.id].lipstick){const lips=document.createElement('span');lips.className='lip-color';el.append(lips);}}
 el.addEventListener('pointerdown',e=>startDrag(e,p));el.addEventListener('click',()=>{if(p.kind==='cat'){feedCat(p);return;}if(p.fixed)openLid(p.id);else if(p.lidFor&&p.closed)openLid(p.lidFor);select(p.id);});el.addEventListener('focus',()=>select(p.id,false));el.addEventListener('keydown',e=>keyMove(e,p));pieces.append(el);}
 $('#companions').replaceChildren();for(const p of state.pieces.filter(p=>(p.kind==='doll'&&p.page===state.page)||p.kind==='cat')){const b=document.createElement('button');b.className='companion'+(p.page===state.page?' present':'');b.setAttribute('aria-label','Bring '+p.name+' to '+names[state.page]);const t=document.createElement('span');t.className='thumb';t.style.display='block';const sp=document.createElement('span');sp.className='sprite';spriteStyle(sp,p);t.append(sp);b.append(t,document.createTextNode(p.id==='girl'?'Bring Lily':p.id==='friend'?'Bring Cherry':'Bring Chibs'));b.onclick=()=>{p.page=state.page;p.x=p.kind==='cat'?77:50;p.y=76;selected=p.id;save();render();say(p.name+' is here');};$('#companions').append(b);}
 $('#pancake-hit').hidden=state.page!==1;$('#chair-front').hidden=state.page!==1||!state.hidingGirl;$('#chair-front').style.cssText=$('.room-art').style.cssText;updateSelection();syncKittyPlay();
}
function position(el,v){el.style.left=v.x+'%';el.style.top=v.y+'%';el.style.width=v.w+'%';el.style.height=v.h+'%';}
function select(id,highlight=true){selected=id;const picked=state.pieces.find(p=>p.id===id);if(picked?.slot&&!picked.attached)heldClothing=id;if(highlight)document.querySelectorAll('.piece').forEach(el=>el.classList.toggle('selected',el.dataset.id===id));updateSelection();}
function updateSelection(){const p=state.pieces.find(q=>q.id===selected);$('#selected-name').textContent=p?p.name:'Pick a piece';$('#selected-hint').textContent=!p?'Drag the dolls and little things. The furniture stays put.':p.fixed?'This stays on the desk. Tap it to lift the lid.':p.attached?'Drag to move her. Choose Take off to remove this piece.':p.slot?'Drag it onto a girl, or tap it and then tap her.':p.lidFor?'Move the lid away, or put it back on its container.':p.kind==='towel'?'Wipe Lily with the towel to dry her loose, wavy hair.':p.kind==='makeup'?'Bring this to a girl’s face to play makeup.':p.kind==='doll'?'Take her anywhere. Lift the blanket to tuck her in.':'Find a cozy spot for the cat.';
 $('#piece-actions').hidden=!p;$('#take-off-piece').hidden=!p?.attached;$('#wear-piece').hidden=!p?.slot||Boolean(p?.attached);$('#remove-outfit').hidden=p?.kind!=='doll';$('#return-piece').hidden=!p||p.fixed;
}
function detach(p){if(!p.attached)return;const v=visual(p);p.x=v.x;p.y=v.y;p.page=v.page;delete p.attached;}
function startDrag(e,p){if(e.button!==0)return;if(state.page===1&&(p.kind==='doll'||p.slot)){stopClosetPlay();state.closetActivity='free';}const targetGirl=p.kind==='doll'?p:p.attached?state.pieces.find(q=>q.id===p.attached):null;if(targetGirl&&heldClothing){const clothing=state.pieces.find(q=>q.id===heldClothing);if(clothing&&clothing.page===targetGirl.page){wear(clothing,targetGirl);heldClothing=null;save();}}select(p.id);if(p.fixed)return;e.preventDefault();const source=e.currentTarget,moving=p.attached?state.pieces.find(q=>q.id===p.attached):p,el=document.querySelector(`[data-id="${moving.id}"]`),v=visual(moving),rect=$('#room').getBoundingClientRect();if(!p.attached)p.closed=false;drag={id:moving.id,el,source,startX:e.clientX,startY:e.clientY,offsetX:e.clientX-rect.left-v.x/100*rect.width,offsetY:e.clientY-rect.top-v.y/100*rect.height,moved:false};source.setPointerCapture(e.pointerId);el.classList.add('dragging');el.style.zIndex=100;for(const q of state.pieces.filter(q=>q.attached===moving.id)){const worn=document.querySelector(`[data-id="${q.id}"]`);if(worn)worn.style.zIndex=101;}source.addEventListener('pointermove',moveDrag);source.addEventListener('pointerup',endDrag,{once:true});source.addEventListener('pointercancel',cancelDrag,{once:true});}
function moveDrag(e){if(!drag)return;const p=state.pieces.find(q=>q.id===drag.id),rect=$('#room').getBoundingClientRect();if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>3)drag.moved=true;const d=dims(p);p.x=clamp((e.clientX-rect.left-drag.offsetX)/rect.width*100,d.w*.35,100-d.w*.35);p.y=clamp((e.clientY-rect.top-drag.offsetY)/rect.height*100,d.h*.35,100-d.h*.35);position(drag.el,visual(p));if(p.kind==='doll')for(const q of state.pieces.filter(q=>q.attached===p.id)){const el=document.querySelector(`[data-id="${q.id}"]`);if(el)position(el,visual(q));}}
function endDrag(e){if(!drag)return;const p=state.pieces.find(q=>q.id===drag.id),wasMoved=drag.moved;drag.source.removeEventListener('pointermove',moveDrag);drag.source.removeEventListener('pointercancel',cancelDrag);drag=null;if(wasMoved)drop(p);else if(p.lidFor)openLid(p.lidFor);else if(p.kind==='cat')feedCat(p);save();render();}
function cancelDrag(){if(!drag)return;drag.source.removeEventListener('pointermove',moveDrag);drag=null;save();render();}
function nearestGirl(p){return state.pieces.filter(q=>q.kind==='doll'&&q.page===p.page).sort((a,b)=>Math.hypot(p.x-a.x,p.y-a.y)-Math.hypot(p.x-b.x,p.y-b.y))[0];}
function wear(p,girl){if(!p.slot||!girl)return false;playSound('dress');for(const q of state.pieces.filter(q=>q.attached===girl.id&&q.slot===p.slot))putBack(q);p.attached=girl.id;p.page=girl.page;heldClothing=null;say(p.name+' on');return true;}
function feedCat(cat){playSound('kitty');state.catFed=!state.catFed;state.catPlaying=false;if(cat.page===0){cat.x=83;cat.y=77;}save();render();say(state.catFed?'Chibs is eating':'Chibs has stopped eating');}function drop(p){if(p.kind==='doll'&&p.page===2){state.bathing=p.x>12&&p.x<88&&p.y>55&&p.y<88;if(state.bathing){playSound('splash');state.wetHair=true;state.highPonytail=false;p.x=48;p.y=64;state.makeup[p.id]={};say('Bath time');}}if(p.kind==='toothbrush'||p.kind==='soap'||p.kind==='towel'){const girl=nearestGirl(p);if(girl&&Math.abs(p.x-girl.x)<girl.w*.65&&Math.abs(p.y-girl.y)<dims(girl).h*.8){if(p.kind==='toothbrush'){state.brushed=girl.id;say('Brush, brush — sparkling clean');}else{state.makeup[girl.id]={};if(p.kind==='towel'){state.wetHair=false;state.highPonytail=false;playSound('cloth');}say(p.kind==='soap'?'A little soapy wash':'All dry — soft, loose waves!');}putBack(p);}}if(p.kind==='doll'&&p.page===0&&p.x>15&&p.x<70&&p.y>35&&p.y<69){p.x=37;p.y=55;state.blanketOpen=false;say('All tucked in');}if(p.kind==='doll'&&p.page===1&&p.x<40&&p.y>50){state.snacking=p.id;say('Pancake time');}if(p.kind==='cat'&&!(p.page===1&&p.x>70&&p.y>60))state.catPlaying=false;if(p.kind==='cat'&&p.page===1&&p.x>70&&p.y>60){state.catPlaying=true;state.catFed=false;p.x=84;p.y=84;playSound('kitty');say('Chibs is pulling the sponge');}if(p.slot){const girl=nearestGirl(p);if(girl&&Math.abs(p.x-girl.x)<girl.w*.65&&Math.abs(p.y-girl.y)<dims(girl).h*.7)wear(p,girl);}if(p.kind==='makeup'){const girl=nearestGirl(p);if(girl&&Math.abs(p.x-girl.x)<girl.w*.6&&Math.abs(p.y-girl.y)<dims(girl).h*.7){state.makeup[girl.id]={...(state.makeup[girl.id]||{}),[p.id==='lipstick'?'lipstick':'blush']:true};say(p.id==='lipstick'?'Strawberry lipstick on her lips':'Rosy blush on her cheeks');putBack(p);}}
 if(p.lidFor){const base=state.pieces.find(q=>q.id===p.lidFor);if(p.page===base.page&&Math.hypot(p.x-base.x,p.y-base.y)<10){const def=definitions.find(q=>q.id===p.id);p.x=def.x;p.y=def.y;p.closed=true;say('Lid back on');}}}
function openLid(id){const lid=state.pieces.find(p=>p.lidFor===id);if(!lid)return;lid.closed=false;lid.x=clamp(lid.x+17,8,90);lid.y=clamp(lid.y+15,8,90);save();render();say('Lid open');}
function putBack(p){const original=definitions.find(q=>q.id===p.id);Object.assign(p,original);if(!original.attached)delete p.attached;}
function keyMove(e,p){if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter',' '].includes(e.key))return;e.preventDefault();select(p.id);if(e.key==='Enter'||e.key===' '){if(p.fixed||p.lidFor)openLid(p.lidFor||p.id);return;}if(p.fixed)return;const focusId=p.id;if(p.attached)p=state.pieces.find(q=>q.id===p.attached);p.closed=false;const step=e.shiftKey?5:1;p.x=clamp(p.x+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0),5,95);p.y=clamp(p.y+(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0),5,95);save();render();document.querySelector(`[data-id="${focusId}"]`)?.focus({preventScroll:true});}
function page(n){stopClosetPlay();state.closetActivity=null;const meeting=n===1;stopDialogue();playSound('page');if(!Number.isInteger(n)||n<0||n>3)throw new Error('Choose a page from 0 to 3');state.page=n;state.opened=true;state.bathing=false;selected=null;for(const girl of state.pieces.filter(p=>p.kind==='doll')){girl.page=n===1?1:girl.id==='girl'?(n===2?2:0):3;if(girl.page!==n)continue;girl.x=n===1?(girl.id==='girl'?32:70):50;girl.y=77;if(n===0&&!state.blanketOpen&&girl.id==='girl'){girl.x=37;girl.y=55;}}save();render();if(meeting)startClosetPlay();}
$('#sound-toggle').onclick=()=>{state.soundMuted=!state.soundMuted;if(state.soundMuted)stopDialogue();save();render();if(!state.soundMuted){playSound('dress');if(state.page===1)greetGirls();}};$('#open-book').onclick=()=>{playSound('page');state.opened=true;save();render();if(state.page===1)startClosetPlay();};$('#home').onclick=$('#close-book').onclick=()=>{playSound('page');stopDialogue();stopClosetPlay();state.opened=false;state.coverSide='front';save();render();};document.querySelectorAll('button[data-page]').forEach(b=>b.onclick=()=>page(+b.dataset.page));$('#previous').onclick=()=>page(state.page-1);$('#next').onclick=()=>{if(state.page===3){playSound('page');state.opened=false;state.coverSide='back';save();render();}else page(state.page+1);};$('#open-from-back').onclick=()=>page(3);
function toggleBed(){playSound('cloth');state.blanketOpen=!state.blanketOpen;const girl=state.pieces.find(p=>p.id==='girl');if(!state.blanketOpen){girl.page=0;girl.x=37;girl.y=55;state.catFed=false;}save();render();say(state.blanketOpen?'Good morning!':'All tucked in');}$('#feed-girl').onclick=eatTogether;$('#pancake-hit').onclick=eatTogether;$('#play-kitty').onclick=()=>{const cat=state.pieces.find(p=>p.id==='cat');cat.page=1;cat.x=84;cat.y=84;state.catPlaying=!state.catPlaying;state.catFed=false;if(state.catPlaying)playSound('kitty');save();render();say(state.catPlaying?'Chibs is pulling the sponge':'Chibs is resting');};$('#feed-kitty').onclick=()=>{const girl=state.pieces.find(p=>p.id==='girl'),cat=state.pieces.find(p=>p.id==='cat');girl.page=0;girl.x=50;girl.y=78;cat.page=0;cat.x=83;cat.y=77;state.catFed=true;save();render();say('She gives Chibs breakfast');};$('#blanket').onclick=toggleBed;$('#bed-toggle').onclick=()=>{if(!state.blanketOpen)toggleBed();};$('#tuck-girl').onclick=()=>{const girl=state.pieces.find(p=>p.id===selected&&p.kind==='doll')||state.pieces.find(p=>p.id==='girl');girl.page=0;girl.x=37;girl.y=55;state.blanketOpen=false;state.catFed=false;save();render();say('Tucked in under the blanket');};$('#room').addEventListener('click',e=>{if(!['room','pieces'].includes(e.target.id))return;const r=$('#room').getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;if(state.page===0&&x>5&&x<80&&y>52&&y<78)toggleBed();if(state.page===1&&x<42&&y>61&&y<83)$('#feed-girl').click();if(state.page===1&&x>74&&y>61)$('#play-kitty').click();});
$('#wear-piece').onclick=()=>{const p=state.pieces.find(q=>q.id===selected);if(!p)return;const girl=nearestGirl(p);if(!girl){say('Bring a girl to this page first');return;}wear(p,girl);save();render();};
function takeOff(p){if(!p?.attached)return;playSound('cloth');detach(p);p.x=clamp(p.x+(p.x<50?22:-22),10,90);p.y=clamp(p.y+8,10,90);heldClothing=null;}$('#take-off-piece').onclick=()=>{const p=state.pieces.find(q=>q.id===selected);takeOff(p);save();render();say('Taken off — place it wherever you like');};$('#remove-outfit').onclick=()=>{for(const p of state.pieces.filter(q=>q.attached===selected))takeOff(p);save();render();say('Clothes are beside her');};
$('#return-piece').onclick=()=>{const p=state.pieces.find(q=>q.id===selected);if(p&&!p.fixed){putBack(p);save();render();say('Back in place');}};
$('#sponge-toy').onclick=()=>$('#play-kitty').click();$('#bath-hit').onclick=()=>{playSound('splash');const girl=state.pieces.find(p=>p.id==='girl');girl.page=2;girl.x=48;girl.y=64;state.bathing=true;state.wetHair=true;state.highPonytail=false;state.makeup[girl.id]={};save();render();say('Splash — into the bath');};$('#help').onclick=()=>$('#help-dialog').showModal();$('#share').onclick=()=>$('#share-dialog').showModal();$('#reset').onclick=()=>$('#reset-dialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#confirm-reset').onclick=()=>{stopDialogue();stopClosetPlay();state.closetActivity=null;state.pieces=definitions.map(d=>({...d}));state.makeup={};state.blanketOpen=false;state.catFed=false;state.catPlaying=false;state.snacking=null;state.bathing=false;state.wetHair=false;state.highPonytail=false;state.brushed=null;selected=null;save();render();$('#reset-dialog').close();say('Everything is back in place');};
async function asData(url){if(url.startsWith('data:'))return url;const r=await fetch(url);if(!r.ok)throw new Error('Artwork could not be loaded');const blob=await r.blob();return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});}
$('#download').onclick=async()=>{const b=$('#download');b.disabled=true;$('#download-status').textContent='Packing your little book…';try{const [css,js,...images]=await Promise.all([window.BOOK_CSS||fetch('style.css').then(r=>{if(!r.ok)throw Error();return r.text();}),window.BOOK_JS||fetch('app.js').then(r=>{if(!r.ok)throw Error();return r.text();}),...Object.values(art).map(asData)]);const doc=document.documentElement.cloneNode(true);doc.removeAttribute('style');doc.querySelector('#pieces').replaceChildren();doc.querySelector('#companions').replaceChildren();doc.querySelector('.room-art').removeAttribute('style');doc.querySelector('#blanket').removeAttribute('style');doc.querySelector('#bath-front').removeAttribute('style');doc.querySelector('#chair-front').removeAttribute('style');doc.querySelector('#sponge-drawing').removeAttribute('style');doc.querySelector('#dialogue').hidden=true;doc.querySelectorAll('dialog').forEach(d=>d.removeAttribute('open'));doc.querySelector('#download').disabled=false;doc.querySelector('#download-status').textContent='The copy includes the artwork and works offline.';doc.querySelector('#initial-state').textContent=JSON.stringify({...state,opened:true});const map=Object.fromEntries(Object.keys(art).map((key,i)=>[key,images[i]]));let inlineCss=css.replace(/@import\s+url\([^)]*\);/,'');for(const key of Object.keys(art))inlineCss=inlineCss.replaceAll("url('assets/"+key+".png')",'var(--art-'+key+')');const style=document.createElement('style');style.textContent=inlineCss;doc.querySelector('link[rel="stylesheet"]')?.replaceWith(style);const script=doc.querySelector('script[src^="app.js"]')||doc.querySelector('#game-code');const code=document.createElement('script');code.id='game-code';code.textContent='window.BOOK_ASSETS='+JSON.stringify(map)+';window.BOOK_CSS='+JSON.stringify(inlineCss)+';window.BOOK_JS='+JSON.stringify(js)+';\n'+js;script.replaceWith(code);let html='<!doctype html>\n'+doc.outerHTML;const url=URL.createObjectURL(new Blob([html],{type:'text/html'}));const a=document.createElement('a');a.href=url;a.download='Strawberry-Butter-Playbook.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);$('#download-status').textContent='Your playable book is ready. Send the downloaded file to a friend.';}catch{$('#download-status').textContent='The download did not finish. Please try again while connected.';}finally{b.disabled=false;}};
if(window.BOOK_ASSETS)Object.assign(art,window.BOOK_ASSETS);for(const key of Object.keys(art))document.documentElement.style.setProperty('--art-'+key,`url("${art[key]}")`);
render();
try{document.modelContext?.registerTool({name:'strawberry_book_state',description:'Read the current page and positions of the movable pieces.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({page:state.page,pieces:state.pieces.map(p=>({id:p.id,page:visual(p).page,x:visual(p).x,y:visual(p).y,fixed:!!p.fixed,attached:p.attached||null}))})});document.modelContext?.registerTool({name:'move_strawberry_piece',description:'Move a movable piece to a fixed book page and position.',inputSchema:{type:'object',properties:{id:{type:'string'},page:{type:'integer',minimum:0,maximum:3},x:{type:'number',minimum:5,maximum:95},y:{type:'number',minimum:5,maximum:95}},required:['id','page','x','y'],additionalProperties:false},execute:input=>{if(!input||typeof input!=='object')throw Error('A piece and position are required');const p=state.pieces.find(p=>p.id===input.id);if(!p||p.fixed||!Number.isInteger(input.page)||input.page<0||input.page>3||![input.x,input.y].every(v=>Number.isFinite(v)&&v>=5&&v<=95))throw Error('Choose a movable piece and a valid position');detach(p);p.page=input.page;p.x=input.x;p.y=input.y;p.closed=false;page(input.page);save();render();return{id:p.id,page:p.page,x:p.x,y:p.y};}});}catch{}
